apiVersion: v1
kind: Secret
metadata:
  name: quobyte-admin-secret
  namespace: quobyte
type: "kubernetes.io/quobyte"
data:
  # echo -n "value" | base64 gives the base64 encoded data for 'value'
  
  # Base64 encoded Quobyte API user name. Key must be 'user'.
  # Update data (YWRtaW4=) with base64 encoded API user name for your Quobyte deployment.
  user: YWRtaW4=
  # Base64 encoded Quobyte API password. Key must be 'password'.
  # Update data (cXVvYnl0ZQ==) with base64 encoded API password for your Quobyte deployment.
  password: cXVvYnl0ZQ==
  # The user and password information is used to commuicate with Quobyte deployment thorugh API.
  # Your API credentials must have volume create and delete capabilities to use dynamic provisioning.