kind: PersistentVolume
apiVersion: v1
metadata:
  name: preprovisoned-quobyte-csi
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  # Delete Reclaim policy does not work with CSI for pre-provisioned volumes
  persistentVolumeReclaimPolicy: Retain
  storageClassName: quobyte-csi
  csi:
    driver: csi.quobyte.com
    # VolumeHandle should be of the format <TENANT_UUID/NAME>|<VOLUME_UUID/NAME>
    volumeHandle: "My Tenant|test"
    # fsType is required, if missed volume mount fails with unclear failure event logs
    fsType: ext4 
    readOnly: false
    nodePublishSecretRef:
      name: quobyte-admin-secret
      namespace: quobyte
