apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: quobyte-csi
# provisioner must be csi.quobyte.com
provisioner: csi.quobyte.com
parameters:
  quobyteTenant: "My Tenant"
  # secret is used for dynamic volume provisioning.
  # The user credentials provided in this secret must have
  # volume create/delete permissions for `quobyteTenant` above.
  csiProvisionerSecretName: "quobyte-admin-secret"
  csiProvisionerSecretNamespace: "quobyte"
  # Quobyte volume configuration
  quobyteConfig: "BASE"
  createQuota: "False"
reclaimPolicy: Retain