apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: quobyte-csi
# provisioner must be csi.quobyte.com
provisioner: csi.quobyte.com
# Should be set to 'true' to expand volume size.
# Volume shrinking is not possible with this feature.
# Quobyte volumes by default are not size restricted,
# volume expansion is only required if volume is created
# with quota (by setting parameters.createQuota: true).
allowVolumeExpansion: true
parameters:
  quobyteTenant: "My Tenant"
  # secret is used for dynamic volume provisioning.
  # The user credentials provided in this secret must have
  # volume create/delete permissions for `quobyteTenant` above.
  csi.storage.k8s.io/provisioner-secret-name: "quobyte-admin-secret"
  csi.storage.k8s.io/provisioner-secret-namespace: "quobyte"
  # Resize volume requires secrets to commuicate with Quobyte API
  csi.storage.k8s.io/controller-expand-secret-name: "quobyte-admin-secret"
  csi.storage.k8s.io/controller-expand-secret-namespace: "quobyte"
  # Quobyte volume configuration
  quobyteConfig: "BASE"
  # creates quota for the volume if set to true. The size of the Quota
  # is the storage requested in PVC. If false, creates unrestricted size volume.  
  createQuota: "true"
  user: root
  group: root
  accessMode: "777"
reclaimPolicy: Retain