# This must be created for the pre-provisioned volume snapshot content
# based on https://kubernetes.io/docs/concepts/storage/volume-snapshots/#volume-snapshot-contents

apiVersion: snapshot.storage.k8s.io/v1beta1
kind: VolumeSnapshotContent
metadata:
  name: snapcontent-pre-provisioned
spec:
  deletionPolicy: Delete
  driver: csi.quobyte.com # your Quobyte CSI driver
  source:
    snapshotHandle: "<Tenant_Name/UUID>|<Volume_Name/UUID>|<Snapshot_Name>"
  volumeSnapshotClassName: quobyte-csi-snapshotclass
  volumeSnapshotRef:
    # Name of the VolumeSnapshot object created in the future,
    # see volume-snapshot-pre-provisioned.yaml
    # This VolumeSnapshotContent can only bind to VolumeSnapshot create with
    # below matching name and namespace
    name: volume-snapshot-pre-provisioned 
    namespace: default