# If kubectl -f create fails with the following error
# no matches for kind "..." in version ".../v1beta1"
# please try with snapshot.storage.k8s.io/v1
# https://github.com/rook/rook/issues/6819#issuecomment-852059116
apiVersion: snapshot.storage.k8s.io/v1beta1
kind: VolumeSnapshot
metadata:
  # Should match VolumeSnapshotContent.spec.volumeSnapshotRef.name
  # of pre-provisioned VolumeSnapshotContent object
  name: volume-snapshot-pre-provisioned
  # Should match VolumeSnapshotContent.spec.volumeSnapshotRef.namespace
  # of pre-provisioned VolumeSnapshotContent object
  namespace: default
spec:
  source:
    # VolumeSnapshotContent object name
    # Match with the VolumeSnapshotContent.metadata.name
    volumeSnapshotContentName: snapcontent-pre-provisioned 