[[constraint]]
  name = "github.com/container-storage-interface/spec"
  version = "1.1.0"

[[constraint]]
  branch = "master"
  name = "github.com/golang/glog"

[[constraint]]
  name = "github.com/quobyte/api"
  version = "0.1.5"