[[constraint]]
  name = "github.com/container-storage-interface/spec"
  version = "1.1.0"

[[constraint]]
  name = "k8s.io/klog"
  version = "0.4.0"

[[constraint]]
  name = "github.com/quobyte/api"
  version = "0.1.5"