kind: Service
apiVersion: v1
metadata:
  name: quobyte-csi-attacher
  labels:
    app: quobyte-csi-attacher
spec:
  selector:
    app: quobyte-csi-attacher
  ports:
    - name: quobyte-csi-attacher
      port: 7820
---
kind: StatefulSet
apiVersion: apps/v1beta1
metadata:
  name: quobyte-csi-attacher
spec:
  serviceName: "quobyte-csi-attacher"
  replicas: 1
  template:
    metadata:
      labels:
        app: quobyte-csi-attacher
    spec:
      serviceAccount: csi-attacher
      containers:
        - name: csi-attacher
          image: quay.io/k8scsi/csi-attacher:v0.4.2
          args:
          # --v=5 logs user credentials
            - "--v=3"
            - "--csi-address=$(ADDRESS)"
          env:
            - name: ADDRESS
              value:  /var/lib/csi/sockets/pluginproxy/csi.sock
          imagePullPolicy: "IfNotPresent"
          volumeMounts:
            - name: socket-dir
              mountPath: /var/lib/csi/sockets/pluginproxy/
        - name: quobyte-csi-attacher
          image: quay.io/venkat_443/csi:v0.3.0-rc
          args :
            - "--csi_socket=$(CSI_ENDPOINT)"
            - "--quobyte_mount_path=$(QUOBYTE_MOUNT_PATH)"
            - "--node_name=$(KUBE_NODE_NAME)"
            - "--api_url=$(QUOBYTE_API_URL)"
          env:
            - name: CSI_ENDPOINT
              value: unix:///var/lib/csi/sockets/pluginproxy/csi.sock
            - name: QUOBYTE_MOUNT_PATH
              value: /mnt/quobyte/mounts
            - name: QUOBYTE_API_URL
              valueFrom:
                configMapKeyRef:
                  name: quobyte-csi-config
                  key: quobyte.apiURL # Quobyte API URL
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          imagePullPolicy: "Always"
          volumeMounts:
            - name: socket-dir
              mountPath: /var/lib/csi/sockets/pluginproxy/
      volumes:
        - name: socket-dir
          emptyDir: {}