quobyte:
  # apiURL should be of the form http(s)://<ip or resolvable host>:<port>
  # Example Quobyte API: http://hydrogen.quobyte.com:26801
  apiURL: "http://10.125.2.77:10330" 
  
  # Quobyte clinet should be deployed with <clientMountPoint>/mounts
  # For example, if you set clientMountPoint: /mnt/quobyte then quobyte
  # client should be deployed with /mnt/quobyte/mounts as the mount point
  clientMountPoint: /mnt/quobyte
  
  # Should be a valid DNS name. StorageClass.provisioner must 
  # be match the value configured here
  csiProvisionerName: csi.quobyte.com 
  
  # When set to true, uses PVC.namespace as Quobyte tenant.
  # This does not create tenants automatically, your storage system must
  # have tenants that match the namespace.
  useK8SNamespaceAsTenant: false 

  # Set this to true to enable Quobyte access keys. Then, add access key
  # information to your K8S secret and use this secret in StorageClass as
  # mount secret. Quobyte-CSI and Client uses access key information
  # from the mount secret to securely mount volumes.
  # When access keys are enabled in CSI driver, Quobyte client must also be 
  # enabled with access keys. To enable access keys on native client,
  # add "enable-access-contexts" in /etc/quobyte/client-service.cfg.
  # For container based client configuration, see client.yaml definition.
  enableAccessKeys: false
  
  # Set to true to deploy csi driver with pod security policies.
  # Change required ONLY if you have pod security policies enabled K8S environment.
  podSecurityPolicies: false
   
  # The dev configuration is intended for Quobyte Developers and internal use.
  # Please do NOT change the dev: configuration unless otherwise adviced to change.
  dev:
    csiImage: quay.io/quobyte/csi:3.0-pre
    # k8s sidecar containers (https://github.com/kubernetes-csi/)
    k8sProvisionerImage: quay.io/k8scsi/csi-provisioner:v1.6.0
    k8sClusterDriverRegistrarImage: quay.io/k8scsi/csi-cluster-driver-registrar:v1.0.1
    k8sResizerImage: quay.io/k8scsi/csi-resizer:v0.5.0
    k8sNodeRegistrarImage: quay.io/k8scsi/csi-node-driver-registrar:v1.3.0
    k8sAttacher: quay.io/k8scsi/csi-attacher:v2.2.0