apiVersion: v1
kind: Pod
metadata:
  name: ngnix-psp-demo
spec:
  containers:
  - name: server
    image: nginxinc/nginx-unprivileged:1.16
    ports:
      - containerPort: 80
    volumeMounts:
      - mountPath: /usr/share/nginx/html
        name: quobytepvc
  volumes:
    - name: quobytepvc
      persistentVolumeClaim:
        claimName: quobyte-csi-test