apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: example-psp-role
  namespace: psp-example # role and service account must be in the same namespace
rules:
- apiGroups:
  - extensions
  resourceNames:
  - example-psp # PSP name from psp-example-definition.yaml
  resources:
  - podsecuritypolicies
  verbs:
  - use
- apiGroups: [""]
  resources: ["pods"]
  verbs:  ['*']
- apiGroups: [""]
  resources: ["persistentvolumeclaims"]
  verbs:  ['*']
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: example-psp-RoleBinding
  namespace: psp-example # rolebinding and service account must be in the same namespace
roleRef:
  kind: Role
  name: example-psp-role
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: psp-user # service account
  namespace: psp-example